apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stablediffusion-serve-gpu
  name: stablediffusion-serve-gpu
spec:
  selector:
    matchLabels:
      app: stablediffusion-serve-gpu
  template:
    metadata:
      labels:
        app: stablediffusion-serve-gpu
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: amd-nvidia
      serviceAccountName: appsimulator
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: app
        image: 133573815653.dkr.ecr.us-west-2.amazonaws.com/stablediffusion:amd64-cuda
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        command: ["/start.sh"]
        args: ["run"]
        resources:
          limits:
            nvidia.com/gpu: "4"
        lifecycle:
          postStart:
            exec:
              command: ["/create_node_port_svc.sh"]
          preStop:
            exec:
              command: ["/bin/sh","-c","kubectl delete svc `kubectl get svc|grep $POD_NAME | awk '{print $1}'`"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
