apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gs-prediction-stats 
    release: r1.12 
  name: gs-prediction-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gs-prediction-stats
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gs-prediction-stats
    spec:
      nodeSelector:
        lifecycle: spot
        title: minecraft
      containers:
      - env:
        - name: LEVEL
          value: world
        - name: ONLINE_MODE
          value: "true"
        - name: JVM_OPTS
          value: -Xmx512M -Xms512M
        image: 356566070122.dkr.ecr.us-west-2.amazonaws.com/gs-prediction-stats
        imagePullPolicy: Always
        name: gs-prediction-stats
        command: ["/start.py"]
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
      schedulerName: default-scheduler
